name: Generate Permanent Keystore
on: [push]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"
          
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v -keystore permanent-release.keystore -alias release -keyalg RSA -keysize 2048 -validity 10000 -storepass neuroguard2026 -keypass neuroguard2026 -dname "CN=NeuroGuard, OU=App, O=NeuroGuard, L=Barcelona, ST=Catalunya, C=ES"
          keytool -export -rfc -keystore permanent-release.keystore -alias release -file upload_certificate.pem -storepass neuroguard2026
          
      - name: Upload Keystore and PEM
        uses: actions/upload-artifact@v4
        with:
          name: permanent-keystore-and-pem
          path: |
            permanent-release.keystore
            upload_certificate.pem
